apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"toolchain.openshift.dev/v1alpha1","kind":"Installation","metadata":{"name":"example-installation"},"spec":{"size":3}}]'
    capabilities: Basic Install
  name: toolchain-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CodeReady Toolchain
      displayName: CodeReady Toolchain Installation
      kind: Installation
      name: installation.openshift.dev
#      specDescriptors:
#      - description: Namespace where OpenShift Pipelines is installed
#        displayName: Target Namespace
#        path: targetNamespace
#        x-descriptors:
#        - urn:alm:descriptor:com.tectonic.ui:label
#      statusDescriptors:
#      - description: Status of OpenShift Pipelines Installation
#        displayName: Installation Status
#        path: conditions[0].code
#        x-descriptors:
#        - urn:alm:descriptor:com.tectonic.ui:label
#      - description: Version of OpenShift Pipelines installed
#        displayName: OpenShift Pipelines Version
#        path: conditions[0].version
#        x-descriptors:
#        - urn:alm:descriptor:com.tectonic.ui:label
      version: v1alpha1
  description: CodeReady Toolchain Operator
  displayName: CodeReady Toolchain Operator
  install:
    spec:
      deployments:
      - name: toolchain-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: toolchain-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: toolchain-operator
            spec:
              containers:
              - command:
                - toolchain-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: toolchain-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: toolchain-operator
                resources: {}
              serviceAccountName: toolchain-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - toolchain-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - toolchain.openshift.dev
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: toolchain-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
