apiVersion: v1
kind: ConfigMap
metadata:
  name: crt-operators
  namespace: openshift-marketplace
data:
  clusterServiceVersions: |
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        annotations:
          capabilities: Basic Install
          categories: Developer Tools, OpenShift Optional
        creationTimestamp: null
        name: toolchain-operator.v0.0.1
        namespace: placeholder
      spec:
        apiservicedefinitions: {}
        customresourcedefinitions:
          required:
          - description: OpenShift Pipelines is a cloud-native CI/CD solution for building
              pipelines using Tekton concepts which run natively on OpenShift and Kubernetes.
            displayName: OpenShift Pipelines Config
            kind: Config
            name: config.operator.tekton.dev
            version: v1alpha1
          - description: A Kube-native development solution that delivers portable and collaborative
              developer workspaces in OpenShift.
            displayName: Red Hat CodeReady Workspaces
            kind: CheCluster
            name: checlusters.org.eclipse.che
            version: v1
        description: CodeReady Toolchain Operator
        displayName: CodeReady Toolchain
        install:
          spec:
            deployments:
            - name: toolchain-operator
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    name: toolchain-operator
                strategy: {}
                template:
                  metadata:
                    labels:
                      name: toolchain-operator
                  spec:
                    containers:
                    - command:
                      - toolchain-operator
                      env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: toolchain-operator
                      image: REPLACE_IMAGE
                      imagePullPolicy: Always
                      name: toolchain-operator
                      resources: {}
                    serviceAccountName: toolchain-operator
            permissions:
            - rules:
              - apiGroups:
                - ""
                resources:
                - pods
                - services
                - services/finalizers
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                verbs:
                - '*'
              - apiGroups:
                - apps
                resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
                verbs:
                - '*'
              - apiGroups:
                - monitoring.coreos.com
                resources:
                - servicemonitors
                verbs:
                - get
                - create
              - apiGroups:
                - apps
                resourceNames:
                - toolchain-operator
                resources:
                - deployments/finalizers
                verbs:
                - update
              - apiGroups:
                - ""
                resources:
                - pods
                verbs:
                - get
              - apiGroups:
                - apps
                resources:
                - replicasets
                verbs:
                - get
              serviceAccountName: toolchain-operator
          strategy: deployment
        installModes:
        - supported: true
          type: OwnNamespace
        - supported: true
          type: SingleNamespace
        - supported: true
          type: MultiNamespace
        - supported: true
          type: AllNamespaces
        maturity: alpha
        provider: {}
        version: 0.0.1
      status:
        certsLastUpdated: null
        certsRotateAt: null
        lastTransitionTime: null
        lastUpdateTime: null
  customResourceDefinitions: ""
  packages: |
    - channels:
      - currentCSV: toolchain-operator.v0.0.1
        name: alpha
      defaultChannel: alpha
      packageName: toolchain-operator
